// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
//
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FaultInjectionEngine.rc
//
#define IDS_PROJNAME                    100
#define IDR_FAULTINJECTIONENGINE        101
#define IDR_ENGINE                      102

#define IDS_PROCESS_ID_AS_NAME          1001
#define IDS_EVENT_LOG_FILE_PATHNAME     1002
#define IDS_MEMORY_DUMP_ADDRESS_INFO    1003
#define IDS_REPORT_OPEN_METHOD_FILTER_FAILED 2000
#define IDS_REPORT_METHOD_INSIDE_PROTECTED_NAMESPACE 2001
#define IDS_REPORT_METHOD_FILTER_LIST_HEADER 2002
#define IDS_REPORT_METHOD_FILTER_LIST_ELEMENT 2003
#define IDS_REPORT_METHOD_FILTER_LIST_FOOTER 2004
#define IDS_REPORT_ENGINE_START         2005
#define IDS_REPORT_FAILED_QUERY_INTERFACE 2006
#define IDS_REPORT_FAILED_GET_FUNCTION_INFO 2007
#define IDS_REPORT_FAILED_GET_MODULE_METADATA 2008
#define IDS_REPORT_FAILED_GET_FUNCTION_ALLOCATOR 2009
#define IDS_REPORT_FAILED_GET_METHOD_PROPS 2010
#define IDS_REPORT_FAILED_GET_TYPE_PROPS 2011
#define IDS_REPORT_FAILED_GET_NESTED_CLASS_PROPS 2012
#define IDS_REPORT_FAILED_GET_FUNCTION_BODY 2013
#define IDS_REPORT_FAILED_EMIT_TYPEREF_TOKEN 2014
#define IDS_REPORT_FAILED_EMIT_METHODREF_TOKEN 2015
#define IDS_REPORT_FAILED_GET_SIG_FROM_TOKEN 2016
#define IDS_REPORT_FAILED_GET_TOKEN_FROM_SIG 2017
#define IDS_REPORT_FAILED_ALLOC         2018
#define IDS_REPORT_FAILED_SET_FUNCTION_BODY 2019
#define IDS_REPORT_FAILED_GET_TOKEN_FROM_TYPESPEC 2020
#define IDS_REPORT_INVALID_SIGNATURE    2021
#define IDS_REPORT_SUCCESSFULLY_MODIFY_METHOD 2022
#define IDS_EVENT_LEVEL_ERROR           10000
#define IDS_END_OF_LINE                 10001
#define IDS_EVENT_LEVEL_WARNING         10001
#define IDS_EVENT_LEVEL_INFO            10002
#define IDS_EVENT_LEVEL_TRACE           10003
#define IDS_EVENT_LEVEL_DUMP            10004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
